version: '3.8'

services:
  api:
    container_name: your_train_api
    build: ./
    depends_on:
      - db
    command: [
      "uvicorn", "api.main:app",
      "--host", "0.0.0.0",
      "--port", "8000"
    ]
    volumes:
      - ./api:/src/api
    ports:
      - ${APP_HOST_PORT}:8000
    restart: always
    env_file:
      - .env
  db:
    container_name: your_train_postgres
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ${POSTGRES_VOLUME_PATH}:/var/lib/postgres/data
    restart: always
    user: "root"