version: '3.8'

services:

  api:
    container_name: api
    build:
      context: .
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - migrations
    ports:
      - '5000:5000'
    command: [
      "uvicorn", "api.main:app",
      "--host", "0.0.0.0",
      "--port", "5000"
    ]

  postgres:
    image: postgres:13.1
    container_name: postgres
    env_file:
      - .env
    environment:
      DB_USER: "${DB_NAME}"
      DB_PASS: "${DB_PASS}"
      DB_NAME: "${DB_NAME}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - "${POSTGRES_VOLUME_PATH}:/var/lib/postgresql/data"

  migrations:
    build:
      context: .
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy
    command: [
      "alembic", "upgrade", "head",
    ]

networks:
  default:
    driver: bridge
